#!/bin/bash

PATH=""

for pathfile in /etc/paths.d/* /etc/paths "${XDG_CONFIG_HOME:-$HOME/.config}/paths"; do
    if [ ! -f "$pathfile" ]; then
        continue
    fi
    while read -r pathline; do
        # ignore lines starting with #
        if [[ $pathline =~ ^#.* ]]; then
            continue
        fi
        PATH+=$pathline:
    done < "$pathfile"
done

echo -n "${PATH%:}"
